java_import(
  name = "parser_combinators",
  jars = ["@scala//:lib/scala-parser-combinators_2.11-1.0.4.jar"],
  visibility = ["//visibility:public"],
)

java_import(
  name = "scala_xml",
  jars = ["@scala//:lib/scala-xml_2.11-1.0.4.jar"],
  visibility = ["//visibility:public"],
)

java_import(
  name = "scala_compiler",
  jars = ["//external:io_bazel_rules_scala/dependency/scala210/scala_compiler"],
  visibility = ["//visibility:public"],
)

